### ISSUE TITLE
cmd/tier: panic/error on pull

### ISSUE THREAD

**Issue by jevon** [tierrun/tier#34]
```
jevon@Jevons-MacBook-Air tierx % go run tier.run/cmd/tier@oauth pull
panic: runtime error: slice bounds out of range [22:21]

goroutine 1 [running]:
golang.org/x/exp/slices.Delete[...]({0x1400033e200?, 0x14000120000?, 0x1?}, 0x5000?, 0x1?)
	/Users/jevon/go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/slices/slices.go:157 +0xf8
main.filterNonTierPlans(...)
	/Users/jevon/go/pkg/mod/tier.run@v0.1.1-0.20220907000054-239344c14a7c/cmd/tier/tier.go:208
main.tier({0x16d537af2?, 0x14000132010?}, {0x14000132010?, 0x14000002340?, 0x14000044768?})
	/Users/jevon/go/pkg/mod/tier.run@v0.1.1-0.20220907000054-239344c14a7c/cmd/tier/tier.go:113 +0x4f0
main.main()
	/Users/jevon/go/pkg/mod/tier.run@v0.1.1-0.20220907000054-239344c14a7c/cmd/tier/tier.go:39 +0x120
exit status 2
```

**Comment by bmizerany** [comment]
@jevon Using the stripe-cli, will you please provide the output for:

```
stripe prices list
```

**Comment by jevon** [comment]
```
{
  "object": "list",
  "data": [
    {
      "id": "price_1LfZ0lDP70AK4tGcdNkb2BEc",
      "object": "price",
      "active": true,
      "billing_scheme": "tiered",
      "created": 1662598471,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": "tier_plan_lemons_1__feature_lemon_stream",
      "metadata": {
        "tier.feature": "feature:lemon-stream",
        "tier.limit": "100",
        "tier.plan": "plan:lemons@1"
      },
      "nickname": "feature:lemon-stream",
      "product": "tier_plan_lemons_1",
      "recurring": {
        "aggregate_usage": "sum",
        "interval": "month",
        "interval_count": 1,
        "trial_period_days": null,
        "usage_type": "metered"
      },
      "tax_behavior": "unspecified",
      "tiers_mode": "graduated",
      "transform_quantity": null,
      "type": "recurring",
      "unit_amount": null,
      "unit_amount_decimal": null
    },
    {
      "id": "price_1LfBx2DP70AK4tGcmw0trK1a",
      "object": "price",
      "active": true,
      "billing_scheme": "tiered",
      "created": 1662509828,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": "tier_plan_beans_2_4__feature_beans",
      "metadata": {
        "tier.feature": "feature:beans",
        "tier.limit": "150",
        "tier.plan": "plan:beans@2.4"
      },
      "nickname": "feature:beans",
      "product": "tier_plan_beans_2_4",
      "recurring": {
        "aggregate_usage": "sum",
        "interval": "month",
        "interval_count": 1,
        "trial_period_days": null,
        "usage_type": "metered"
      },
      "tax_behavior": "unspecified",
      "tiers_mode": "graduated",
      "transform_quantity": null,
      "type": "recurring",
      "unit_amount": null,
      "unit_amount_decimal": null
    },
    {
      "id": "price_1LfBx2DP70AK4tGcs1QU2lcG",
      "object": "price",
      "active": true,
      "billing_scheme": "tiered",
      "created": 1662509828,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": "tier_plan_beans_2_4__feature_song_stream",
      "metadata": {
        "tier.feature": "feature:song-stream",
        "tier.limit": "125",
        "tier.plan": "plan:beans@2.4"
      },
      "nickname": "feature:song-stream",
      "product": "tier_plan_beans_2_4",
      "recurring": {
        "aggregate_usage": "sum",
        "interval": "month",
        "interval_count": 1,
        "trial_period_days": null,
        "usage_type": "metered"
      },
      "tax_behavior": "unspecified",
      "tiers_mode": "graduated",
      "transform_quantity": null,
      "type": "recurring",
      "unit_amount": null,
      "unit_amount_decimal": null
    }
  ],
  "has_more": true,
  "url": "/v1/prices"
}
```

**Comment by bmizerany** [comment]
@jevon Can you update with `-d limit=100`? Also, please be mindful of the keys being pasted into the issue :)
